### ISSUE TITLE
Setting a bit outside of BitVec length

### ISSUE THREAD

**Issue by DarkEld3r** [myrrlyn/bitvec#20]
It isn't an issue, more like a feature request, but I had several situations in which I need to do the following:
```rust
if vec.len() <= bit {
    vec.resize(bit + 1, false);
}
vec.set(bit, true);
```
Am I missing a specific method that does exactly that? I would like to send a pull request if you think that can be useful.

**Comment by myrrlyn** [comment]
I am hesitant to add a vector manipulation method that is not present in `std::vec::Vec`, especially one that may hide a reallocation event. I'm not immediately opposed, since `BitVec` reallocates 8-64x less often than `Vec`, but at first glance I expect any such method would require user control over whether the `resize` call is allowed to reallocate, and would have to signal whether it actually set the bit or exited early.

I'll think about it; this seems like a valid use case (I hit it in my Sieve example) so I'm not inclined to close, but I don't have a clear idea of what to immediately add either.

Alexander Payne
Software Engineer, Space Dynamics Laboratory
________________________________
