### ISSUE TITLE
Implement left/right shift for BitSlice

### ISSUE THREAD

**Issue by aleksmelnikov** [myrrlyn/bitvec#23]
It will be good to add `left shift`, `right shift` in-place methods for `BitSlice` like existed `rotate_left`, `rotate_right`. I mean the [Logical shift](https://en.wikipedia.org/wiki/Logical_shift).

**Comment by myrrlyn** [comment]
Are the [`ShlAssign` (`<<=`)](https://docs.rs/bitvec/0.14.0/bitvec/slice/struct.BitSlice.html#impl-ShlAssign%3Cusize%3E) and [`ShrAssign` (`>>=`)](https://docs.rs/bitvec/0.14.0/bitvec/slice/struct.BitSlice.html#impl-ShrAssign<usize>) implementations on `BitSlice` sufficient? If not, what are they lacking that could be added?

**Comment by aleksmelnikov** [comment]
@myrrlyn, Ops, I have overlooked these implementations. Thx.

**Comment by myrrlyn** [comment]
Downside of docs this huge; it's really easy to not find things

**Comment by dignifiedquire** [comment]
@myrrlyn what happened to these? I am unable to find them in 0.19

**Comment by myrrlyn** [comment]
I removed the shift operators from the crate because their standard-library counterparts do not have them; I should have moved the behavior into inherent methods, and have done so now. `BitSlice::shift_left` and `BitSlice::shift_right` restore the behavior. Currently, `BitVec` does not override them to include `.extend()`/`.truncate()` behavior.
