### ISSUE TITLE
Macros that implement AsRef and AsMut break an existing code

### ISSUE THREAD

**Issue by Fotosmile** [myrrlyn/bitvec#35]
Hi. Recently I was needed to work with bits, and I had chosen your crate. But as soon as I imported `BitVec`structure, other modules showed errors like `cannot infer type for 'T'` and `the trait io::Read is not implemented for &[i32]`. I was wondering and have looked a bit closer, why other modules in my crate were broken. The problem was in [`AsRef` and `AsMut` generation for arrays](https://github.com/myrrlyn/bitvec/blob/master/src/bits.rs#L191). 
So, consider we have the code:
```rust
use std::io::{self, Write};

// use bitvec;

pub fn breaks_as_mut() {
    let bytes_to_write = "Hello, world!".as_bytes();

    let mut name_buffer = [0; 5];
    name_buffer.as_mut().write_all(bytes_to_write).unwrap();
}

pub fn breaks_as_ref() {
    let b = [0x05];
    applies_impl_read(b.as_ref()).unwrap();
}

pub fn applies_impl_read(_stream: impl io::Read) -> io::Result<()> {
    Ok(())
}
```
If the `use bitvec` line is commented, everything is fine. But when I uncomment the line, the errors occurred:
```bash
warning: unused import: `bitvec`
 --> src/lib.rs:3:5
  |
3 | use bitvec;
  |     ^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0282]: type annotations needed
 --> src/lib.rs:9:17
  |
9 |     name_buffer.as_mut().write_all(bytes_to_write).unwrap();
  |                 ^^^^^^ cannot infer type for `T`
  |
  = note: type must be known at this point

error[E0277]: the trait bound `&[i32]: std::io::Read` is not satisfied
  --> src/lib.rs:14:5
   |
14 |     applies_impl_read(b.as_ref()).unwrap();
   |     ^^^^^^^^^^^^^^^^^ the trait `std::io::Read` is not implemented for `&[i32]`
...
17 | pub fn applies_impl_read(_stream: impl io::Read) -> io::Result<()> {
   |        -----------------               -------- required by this bound in `applies_impl_read`
   |
   = help: the following implementations were found:
             <&[u8] as std::io::Read>

warning: unused import: `Write`
 --> src/lib.rs:1:21
  |
1 | use std::io::{self, Write};
  |                     ^^^^^

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0277, E0282.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `checkbitvec`.
```
I know that I can replace `name_buffer.as_mut().write_all()` with `(&mut name_buffer[..]).write_all()`, and `applies_impl_read(b.as_ref())` with `applies_impl_read(&b[..])`, but I like to use `as_ref` and `as_mut` alternatives to not so beautiful `&[..]` and `&mut [..]` constructions. So I need to change a lot of code to reduce the errors.
The macro generations `AsRef` and `AsMut` can be turned in to feature that will be by default, and I will disable the feature so my code will not be broken. Or there is exists another solution...
I use rust 1.39.0 on stable-x86_64-unknown-linux-gnu.
Thanks!

**Comment by myrrlyn** [comment]
This is a common problem when using traits that are generic in the *trait*, rather than in the *method*. Rust's type resolver does not handle ambiguity in intermediate positions of expressions, so if an expression such as `item.trait_call()` can denote multiple expansions to multiple types, it will not attempt to choose one.

The problem is that the `.as_ref()` calls can refer to both `<[T; N] as AsRef<[T]>>::as_ref(&[T; N]) -> &[T]` *and* `<[T; N]> as AsRef<BitSlice<_, T>>::as_ref(&[T; N]) -> &BitSlice<_, T>`.

When working with fixed-size arrays, the coercion from `[T; N]` to `[T]` can be accomplished through, as you note, `.as_{ref,mut}()` without any imports (`As{Ref,Mut}` are in the implicit prelude); `.borrow_{,mut}()` with an import (`std::borrow::Borrow{,Mut}` are not), or, as you note, through range indexing (`[..]`). Use of `.as_{ref,mut}()` is generally not preferred except when the result of the method call is going directly to a statically-typed slot, precisely because the call is ambiguous.

For what it's worth, you don't actually need to explicitly reborrow when indexing: the expressions `(&{,mut} value[..]).method()` and `value[..].method()` are equivalent. This also has the advantage of declaring that the value is being interpreted as a slice, rather than creating a view of another type, which is what the `As{Ref,Mut}` traits do.

----

All that said, I've been deliberating whether to remove the `As{Ref,Mut}<BitSlice<_, T>>` implementations as I wrote this. As this issue demonstrates, the `.as_{ref,mut}()` view production does not allow users to specify the type of the view produced *in the method call*: it must be done with a fixed-type binding site (`let view: &View = expr.as_ref();`) or explicit call (`AsRef::<View>>::as_ref(&expr)`. This must be done for production of `BitSlice` views *anyway*, as they have an additional type parameter that cannot be taken from the source expression.

I think the correct thing to do is to remove the `As{Ref,Mut}` implementations, since I provide a trait to produce views that does correctly collect the missing type parameter.

Thanks for this issue; the next minor-version release will remove the traits.

**Comment by Fotosmile** [comment]
Thanks for the problem fix and such a detailed explanation!
