### ISSUE TITLE
Serde Serialize/Deserialize implementation?

### ISSUE THREAD

**Issue by djahandarie** [myrrlyn/bitvec#4]
I've found myself wanting to dump some BitVecs into JSON; it'd be nice if BitVec implemented Serde's Serialize/Deserialize (likely behind a crate feature flag).

**Comment by myrrlyn** [comment]
I'm definitely on board with this; I've had it as a vague to-eventually-do item but as I've never used serde before I don't really know what that entails or how to do it correctly.



I am currently in the middle of a rewrite for the 0.10/1.0 release; I had hoped to finish it before my work was interrupted this winter but I didn't quite make it, and I haven't picked it back up yet.



Something about which I'm unsure would be how to serialize the bit slices - I'm leery of JSON numerics, but a byte array is probably a better format than a string of literal `1` and `0` characters. I'd be delighted to know what your expected behavior is as a guide on how to move forward.



Thanks for your interest and your request!



Alexander Payne



  _____

**Comment by djahandarie** [comment]
Good to hear! I’m no expert on Serde itself, but in terms of the JSON serialization, I manually played around with a couple things.

The first attempt was a JSON array of bools, but this ended up being too inefficient (in terms of on-the-wire representation and eventual in-browser memory representation). I’m not sure if Serde exposes a way to provide multiple serializations, but if it does, also allowing users to pick the underlying int Vec as the serialization might be nice.

FWIW, in my case, I sort of gave up entirely and summarized the BitVec (each entry representing a second) into a Vec (each entry representing how many seconds were 1 in a given minute). I.e., chunking by 60 and counting 1s. For the purpose of my frontend, this level of granularity was all that was required.

Unfortunately this all doesn’t really help answer the question. Though, if only one behavior could be picked, the array of bools is probably the most intuitive one at least.

**Comment by myrrlyn** [comment]
I think I have a reasonable concept of how to accomplish this.

Fundamentally, a `BitSlice` is composed of two structures:

- the handle: a (magically packed) structure of pointer (useless), element count (necessary), head position (necessary), and tail position (necessary)
  - the type parameters `C: Cursor` and `T: Bits` also need to be de/serialized somehow
- the data: a sequence of arbitrary T elements.

The following [RON](https://github.com/ron-rs/ron) is probably a reasonable representation:

```text
BitSlice {
 cursor: "BigEndian" | "LittleEndian" | other?,
 storage: "u8" | "u16" | "u32" | "u64",
 elements: usize,
 head: u8,
 tail: u8,
 data: [
  number,
  number,
 ],
}
```

I am not entirely sure how the `cursor` and `storage` parameters will work, but I'll cross that bridge later. In the meantime, this is the data model I'm going to try out and see how it goes.

**Comment by myrrlyn** [comment]
@djahandarie does commit [19734399](https://github.com/myrrlyn/bitvec/commit/19734399a612dd96b8f936e8a1cbf8405a9e4d3c) address what you want?

**Comment by myrrlyn** [comment]
[`bitvec` 0.11.0](https://crates.io/crates/bitvec/0.11.0) contains a `serde` feature which enables serialization of `BitSlice` in all environments, and de/serialization of `BitBox` and `BitVec` when an allocator exists.
