### ISSUE TITLE
Serde Tests Fail on Certain Architectures

### ISSUE THREAD

**Issue by Alexhuszagh** [myrrlyn/bitvec#44]
On various architectures, where `serde::Serialize` is not implemented for `AtomicU8`, the serde_json tests fail.

```bash
error[E0277]: the trait bound `std::sync::atomic::AtomicU8: serde::Serialize` is not satisfied
  --> tests/serdes.rs:18:13
   |
18 |     let json = serde_json::to_string(&bv).expect("cannot fail to serialize");
   |                ^^^^^^^^^^^^^^^^^^^^^ the trait `serde::Serialize` is not implemented for `std::sync::atomic::AtomicU8`
   |
   = note: required because of the requirements on the impl of `serde::Serialize` for `bitvec::prelude::BitVec<bitvec::order::Msb0, u8>`
   = note: required by `serde_json::to_string`
```

Looking at [serde](https://github.com/serde-rs/serde/blob/a00aee14950baca7de2e334b895e203b013712da/serde/build.rs#L81), it looks like serde::Serialize is only implemented for architectures where it knows std::sync::atomic is know to exist, which is the following architectures:
- x86_64
- i686
- aarch64
- powerpc64
- sparc64
- mips64el

Using `target_arch` to conditionally compile the tests should likely fix the issue.

**Comment by myrrlyn** [comment]
Boy I sure would love to have stable access to the `target_has_atomic` gate so that I can toss it in the `BitStore::Access` associated type conditions and make this impossible to happen! Feature `serde` is valid on those architectures; feature `atomic` is not. The fix is to fake the `std` gates by using `cfg(all(feature = "atomic", any(target_arch = "a_good_computer",…)))` on each `type Access = atomic::AtomicUint;` declaration.

This *also* means I have to figure out a non-awful way to granularly conditionally-enable `BitSlice`'s `Send` and `Sync` impls! Yay.

**Comment by Alexhuszagh** [comment]
Yeah, there is no great solution, but the issue is likely in Serde here. These platforms do support atomics (at least, through Qemu emulation, which should be a good indicator). That being said, it might be easiest to just only run the serde tests on the architectures serde has whitelisted.

**Comment by myrrlyn** [comment]
Current trunk behavior (with the new memory architecture provided through #47) should now remove the requirement that any `Atomic` type implement `Serialize`.

Travis shows success for `cross` targets not listed here. I'm going to mark this as closed, unless anything weird happens in Travis while the rest of the builds churn.
