### ISSUE TITLE
Got a question while playing with bit iterator

### ISSUE THREAD

**Issue by ImmemorConsultrixContrarie** [myrrlyn/bitvec#45]
Are both orderings continuous on whatever endianness? Like I have LE, and both orderings look like this
```
 Lsb0
 1-->   8  9
[10101010][10101010]
        9  8   <--1
               Msb0
```
Or Msb0 ordering on LE machine is something like this?
```
 8   <--1         9
[10101010][10101010]
```

**Comment by myrrlyn** [comment]
I need to make [this document](https://github.com/myrrlyn/bitvec/blob/master/doc/Bit%20Patterns.md#order-addressing) more readable, but this is the step order for all provided order/store combinations.

The technical answer is "bits and bytes are different dimensions, rather than different divisions of a straight line", so it's hard to give a meaningful answer here.

The `u8` store is unaffected by machine byte endianness, so you are guaranteed to have the same interpretation of data on any target with it.

**Comment by ImmemorConsultrixContrarie** [comment]
> 
> 
> I need to make [this document](https://github.com/myrrlyn/bitvec/blob/master/doc/Bit%20Patterns.md#order-addressing) more readable, but this is the step order for all provided order/store combinations.
> 
> The technical answer is "bits and bytes are different dimensions, rather than different divisions of a straight line", so it's hard to give a meaningful answer here.
> 
> The `u8` store is unaffected by machine byte endianness, so you are guaranteed to have the same interpretation of data on any target with it.

I suspect, there could be a problem with `resize()` on BE machines, as it shouldn't be #[cfg] if this assertion will pass.
```
let one = 1_u16;
let ptr: *const u8 = &one as _;
assert_eq!(*ptr, one as u8);
```

**Comment by ImmemorConsultrixContrarie** [comment]
Okay, this assert shouldn't pass; core::ptr::write_unaligned() does somewhat same thing with `replace`:
https://doc.rust-lang.org/src/core/ptr/mod.rs.html#876-881
