### ISSUE TITLE
`split_at_mut` may be unsound

### ISSUE THREAD

**Issue by zesterer** [myrrlyn/bitvec#49]
Hi. I've been implementing a similar API to `bitvec` for ternary recently.

I've come to the conclusion that in compressed encodings (such as 8 bits / 1 byte that `bitvec` uses) `split_at_mut` is unsound on slices that are not byte-aligned since it permits overlapping mutable views of memory.

I'd think this is quite a serious issue, and the code for `split_at_mut` (https://docs.rs/bitvec/0.17.2/src/bitvec/slice/api.rs.html#1220-1223) doesn't seem to address this issue at all.

Is it the case that `split_at_mut` is unsound, or have you found a way to resolve the issue? If so, how?

**Comment by myrrlyn** [comment]
I cannot give a long answer at this time but please see the implementation of BitSlice::set_unchecked and the access::BitAccess trait

The atomic feature selects whether all memory accesses in the crate are atomic or not, and its absence disables multithreading support. This is an overconservative approach (see issue prior to yours) but the summary is that at no point does the crate ever manifest aliased `&mut` references to memory or perform racing accesses.

Versions from 0.10 to ~0.15,or whenever I introduced the trait, are unsound for the exact reason you mention, and must not be used. They will be yanked immediately upon publishing a 1.0.

**Comment by zesterer** [comment]
Interesting, thanks for the response.

Since I'm working on something with similar requirements, do you have any plan for fine-grained mitigation of this issue in the future? I'm wondering whether it might be possible to check whether a write to an overlapped byte has occurred, and then perform an atomic read/write accordingly. I can imagine that properly synchronising this, given the bit-shifting needed to properly encode the bits, might be difficult however.

**Comment by myrrlyn** [comment]
Alright, I have time for a longer answer now:

The `domain` module gives me the information I need to determine whether a particular memory address is known to be unaliased, or aliasing is unknown and should be assumed. In particular, the [`Splat::Left` structure](https://github.com/myrrlyn/bitvec/blob/4cbdc0fb167aced5cf813253cbdd7cbde1cf25c2/src/domain.rs#L39-L43) describes a region of memory that has maybe-aliased edges and a known-unaliased interior. This means that it is sound to, instead of returning a slice of types that enforce either atomic or unthreaded access, a slice of bare `[&Cell<integer>]`.

My work on #47 is currently exploring the direction of defining a new trait implemented only on the actual integer fundamentals, and adjusting `BitStore` to be implemented on the fundamentals, their atomics, and their `Cell`s. By using associated types -- the fundamentals retain their current feature-switched atomic or cell behavior, and the atomics and cells use themselves -- I can retain the behavior of selecting the correct memory access behavior, but encode in the typesystem whether any particular `&BitSlice` reference is known to be over maybe-aliased or known-unaliased memory. The problem here is mainly that this is a *massively* invasive change to be making after the fact, so it's taking a lot of time to ensure that I have the correct behavior.

The end goal is to be able to split any `&BitSlice` into the `domain` tuple of aliased and unaliased regions, allowing work to be done without atomic `lock op` instructions when a region is known to be unaliased by other threads.

It is slower to check whether a particular bit index is aliased and to access accordingly, than it is to unconditionally issue atomic accesses. As such, `BitSlice::set_unchecked` and `<usize as BitSliceIndex>::get_unchecked` -- the only two methods that actually touch memory -- will not be receiving a domain check. Once I get this operational, encoding aliasing in the type system will allow correct, safe, removal of the atomic penalty with an `O(1)` cost per slice rather than `O(n)`.

I will also be publishing a document -- at minimum in this repository, ideally on my blog -- describing the process I used to develop the `domain` module's information, the `access` module's behavior, and the impending feature of encoding alias information into the type system at runtime.

**Comment by myrrlyn** [comment]
`.split_at_mut` is not unsound and [I can prove it](https://github.com/myrrlyn/bitvec/issues/47#issuecomment-591123926).
