### ISSUE TITLE
Iterator speed

### ISSUE THREAD

**Issue by ImmemorConsultrixContrarie** [myrrlyn/bitvec#51]
I made a little iterator benchmark. On my machine the double-pointer iterator (even without folding optimization) is two times faster than original "split_first" iterator.

Though, there are some problems I've met while was playing with iterators:
1. "Try" trait is nightly-only and thus "try_fold" and "try_for_each" couldn't be written in stable Rust.
2. This new iterator could have some problems with orderings other than Lsb0 and Msb0 when optimized for folding; specialization is nightly-only too.
3. Std iterator uses "unchecked_sub" intrinsic in "len()" function. And this is a problem. Because I'm jealous and wanna use it too!

Okay, the latter ain't a real problem, but nightly-only features are. Should it be optimized for "try_fold" (and "try_for_each", "fold", "for_each") at all? More #[cfg]s, now for those nightly things? Even though there's no bench for fold yet, 'cuz it's hard to bench without proper implementation (I hasn't finished it yet), it's easy to write with the new "domain" (good work there!).

And I need a little help with bit pointers: forgot everything I knew about that crate after the month full of problems. So, how could I create two bitmasks, one for the very first bit and one for the last? I think, that's something about index and ((len - index) % sizeof*8), but I just don't know how to get at least one index, lol.

[iter_bench.txt](https://github.com/myrrlyn/bitvec/files/4302523/iter_bench.txt)

**Comment by myrrlyn** [comment]
I am reluctant, but not unwilling, to add a `nightly` feature gate, but it would receive less maintenance than the stable items.

A double-pointer iterator is something I've been vaguely contemplating since seeing its use in the `[T]` iterators. It can be represented as follows:

```rust
#[repr(C)]
struct Iter<O: BitOrder, T: BitStore> {
  //  address of the base element
  front: *const T,
  //  address of the element containing the tail marker
  back: *const T,
  //  semantic count of the first live bit
  head: BitIdx<T::Mem>,
  //  semantic count of the first dead bit
  tail: BitTail<T::Mem>,
}
```

This is easy to construct from a `BitPtr<T>`: 

```rust
impl<T: BitStore> BitPtr<T> {
  fn to_iter(self) -> Iter<T> {
    let (base, head, bits) = self.raw_parts();
    let (elts, tail) = head.span(bits);
    Iter {
      front: base,
      back: base.offset(elts),
      head,
      tail,
    }
  }
}
```

I'll need to come up with a good way to test whether the `(*const T, BitIdx<T::Mem>)` bit pointer has reached the `(*const T, BitTail<T::Mem>` tail marker in order to handle termination, but access to memory is just `BitAccess::get(&*(front as *const T::Access), head)` or construction of a `BitMut<T>` from `(front, head, 1)`. Pretty straightforward.

**Comment by myrrlyn** [comment]
Version 0.18 uses double-pointer iteration, and demonstrates non-trivial acceleration. Thank you for the suggestion, and your work earlier this year! It's really helped me improve the library.
