### ISSUE TITLE
Bitwise operations take ownership

### ISSUE THREAD

**Issue by aaronelmore** [myrrlyn/bitvec#54]
I am not sure if this an issue or something due to a lack of Rust knowledge, but there seems to be a lack of way for efficient bitwise comparisons.  When trying to do something like xor'ing two BitVecs, ownership is moved for the XOR:

```       let bv1 = bv::bitvec![0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
        let bv2 = bv::bitvec![0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0];
        let t = bv1 ^ bv2;
        assert_eq!(t.count_ones(), 3);
        let t2 = bv2 ^ bv1;
        assert_eq!(t2.count_ones(), 3);
```

This fails due to a moved bv1 and bv2. I think this is due to the bitxor trait.
From what I can tell the only way around this is to clone bv1 and bv2 for every operation, which can have performance implications when dealing with a large number of large bitvectors.

Looking at creating a slice like the following doesn't work due to a lack of xor for bitslice.

```
        let bv1 = bv::bitvec![0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
        let bv2 = bv::bitvec![0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0];
        let b1: &bv::BitSlice = &bv1[..];
        let b2: &bv::BitSlice = &bv2[..];

        let t = b1 ^ b2;
        assert_eq!(t.count_ones(), 3);
```

Am I missing something obvious or will a borrowed xor need to be hand rolled?

Thanks!

**Comment by myrrlyn** [comment]
The standard library implements `Arith<Rhs=&Self>`; I do not. That is a bug on my part due to merely not having pasted in enough trait boilerplate, and since you're the first person to be stung by its absence, I just haven't moved it up the todo list.

**Comment by myrrlyn** [comment]
Oh, I see what happened. I implement `Arith<Rhs = impl Iterator<Item = bool>>`, but `BitSlice` recently changed to be `Iterator<Item = &bool>`. You should be able to do `BitVec ^ BitVec.iter().copied()`. I'll still expand the implementation surface to accept iterators over borrows.

**Comment by aaronelmore** [comment]
Thanks for the fast response!
I am not sure I followed the potential solution 100%, but either side of the ^ seems to move, which means both sides have to copied.

This fails to bv1 being moved
```

        let bv1 = bv::bitvec![0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
        let bv2 = bv::bitvec![0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0];
        let t = bv1 ^ bv2.iter().copied();
        assert_eq!(t.count_ones(), 3);
        let t2 = bv2 ^ bv1.iter().copied();
        assert_eq!(t2.count_ones(), 3);
```

**Comment by myrrlyn** [comment]
Yes, the left hand side always moves. This is because `BitVec` is a heap allocation, and preserving the source while creating a new output store would cause a new allocation to occur. You will need to write `bv1.clone() ^ rhs` in order to explicitly duplicate the source vector before acting on it. I do not plan to change that behavior, as implicit allocations are generally considered poor form.

This is an unfortunate consequence of not having any `Copy` types corresponding to direct arrays; I only have borrowed slices and owned allocations.

I should note that the expression `let out = lhs.clone() ^ rhs.iter().copied();` only results in *one* copy event; the expression `.iter().copied()` merely produces `bool` instead of `&bool` when traversing. It's a free operation that only exists to satisfy the type checker.

I'll still rework the trait surface to accept `BitVec sigil &BitVec`, but the left-hand side will always need to be explicitly cloned in order to retain the original vector.

----

Depending on your goals, using `BitVec`'s arithmetic operations may also be the *wrong* thing to do. These operations are provided in order to make working with *any* bit sequence easier, but in order to do this, they are much *slower* than the equivalent loop on their underlying storage would be.

If you control the construction of both `BitVec`s, and know that they are of the same type parameters, this code is uglier, much more narrowly usable, but much faster:

```rust
let bv1: BitVec<_, _> = make();
let bv2: BitVec<_, _> = make();
let out: Vec<_> = bv1.as_slice().clone();

for ((lhs, rhs), dst) in bv1.as_slice().iter().copied()
  .zip(bv2.as_slice().iter().copied())
  .zip(out.iter_mut())
{
  *dst = lhs ^ rhs;
}
```

This specialization can't be put in the trait implementation, or I wouldn't even mention it.

**Comment by aaronelmore** [comment]
Thanks much! I was thinking since the output of XOR is new that it could have been stack allocated without any modification of LHS/RHS. 

I wasn't aware of .iter().copied() so that is good to know.

Your second suggestion seems good. I really want for now a count of XOR bits between controlled bitvectors  (looking for K bitvectors with the smallest hamming distance from a reference bitvec), but I will need a way later of generating AND/XOR bitvec's quickly.

**Comment by myrrlyn** [comment]
I am vaguely working on a way to have array types, but without const-generics they are a lot harder to do.

I completely forgot that [`BitVec::into_vec`](https://docs.rs/bitvec/0.17.3/bitvec/vec/struct.BitVec.html#method.into_vec) exists. It only reëncodes the vector handle without doing anything to the actual owned buffer, so feel free to move between `Vec`/slice and `BitVec`/`BitSlice` types liberally as needed. Bulk operations like Boolean arithmetic are better done with ordinary `Vec`/slice` (at least until I get specialization), and you can easily move between `std` and `bitvec` types to get the behavior best suited to any particular need.

**Comment by myrrlyn** [comment]
Update: coherence rules disallow neighboring impls of `BitAnd<I: Iterator<Item = bool>>` and `BitAnd<I: Iterator<Item = &bool>>`, despite the fact that the trait system does not a type to implement `Iterator` twice.

I will add documentation to the README and to each trait to more clearly explain the movement of the left argument and how to construct right arguments.

**Comment by myrrlyn** [comment]
This behavior remains correct as it stands; the `op=` sigil can be used to borrow its arguments rather than move them, at the cost of explicitly declaring where the new memory is allocated.

**Comment by Korne127** [comment]
Just in case anyone stumbles on this in the future (like me): This information is outdated. 
With version 1.0, #89 has been fixed, which speeds up the native &|^ operators by _a lot_ (as they're natively calculated in batches).

Additionally, the API has been changed so that the supposedly faster code can't be used anymore.

Nevertheless, I was curious and therefore adapted it and tested both against each other using [Criterion](https://github.com/bheisler/criterion.rs).
The result is that in my test, using the ^ operator is now around fifteen times as fast as using the iteration.



Code for reproducibility:
```rust
fn criterion_benchmark(c: &mut Criterion) {
	let vec1 = bitvec![0; 10_000];
	let vec2 = bitvec![1; 10_000];
	c.bench_function("Using ^ operator", |b| {
		b.iter_batched(|| {
			(
				black_box(vec1.clone()),
				black_box(vec2.clone()),
			)
		}, |(vec1, vec2)| {
			let _ = black_box(black_box(vec1) ^ black_box(vec2));
		}, BatchSize::PerIteration)
	});

	c.bench_function("Using ^ iteration", |b| {
		b.iter_batched(|| {
			(
				black_box(vec1.clone()),
				black_box(vec2.clone()),
			)
		}, |(mut vec1, vec2)| {
			let mut out = vec1.clone();
			for ((lhs, rhs), mut dst) in vec1.as_slice().iter().copied()
				.zip(vec2.as_slice().iter().copied())
				.zip(out.iter_mut())
			{
				*dst = lhs ^ rhs;
			}
		}, BatchSize::PerIteration)
	});
}
````
