### ISSUE TITLE
`BitSlice` should expose `as_slice` with same semantics as `BitVec`

### ISSUE THREAD

**Issue by bkchr** [myrrlyn/bitvec#56]
`as_slice` of `BitVec` returns all edges, even partially owned ones. However, `BitSlice::as_slice` only returns full edges.

For an encoder we need to access all the internal data. Currently it requires that we convert `BitSlice` to a `BitVec` temporarily.  It would be nice if we could prevent this conversion :)

**Comment by myrrlyn** [comment]
# `0.17`

Due to potential aliasing of split slices, `as_slice -> &[T]` is undefined behavior if it includes partial edges.

The function [`as_total_slice`](https://docs.rs/bitvec/0.17.4/bitvec/slice/struct.BitSlice.html#method.as_total_slice) provides access to all elements, including partials, at the cost of marking them all as aliased.

For slices with partial edges, this function allows you to view and modify memory outside the boundaries of the `BitSlice` that produced them. Keep in mind that using the `T::Access` type to modify memory backed by a `&BitSlice` is undefined behavior.

I will update the `as_slice` documentation to point to `as_total_slice` as a sibling method.

# Trunk/`0.18`

The changes to the type system in the `0.18` series will allow `as_slice` to have this behavior, and remove the need for `as_total_slice`. Any aliasing event will mark all slices that can observe aliased memory so that they always use an alias-safe type. I believe that current trunk still maintains this separation, but it is no longer necessary, and I will remove it if present.

Trunk is unstable and while I strive to keep each published commit to it a buildable snapshot, you should only switch from crates.io to git if you are willing to accept this instability.

I will accelerate my work on getting `0.18` released.

**Comment by bkchr** [comment]
Ty! For the moment I will just stick to converting it to a `BitVec`.

**Comment by myrrlyn** [comment]
`.as_slice` now (0.18) returns all elements, as it can detect when it must use aliased vs unaliased types. I am going to mark this as closed; please feel free to re&ouml;pen if it turns out that I have in fact not fixed your problem. Thanks for the report!
