### ISSUE TITLE
MAX_ELTS is not public

### ISSUE THREAD

**Issue by kpp** [myrrlyn/bitvec#57]
There is a node in the docs:

```
/// Panics if the number of bits in the vector overflows
/// `BitPtr::<T>::MAX_ELTS`.
```

However I could not find `MAX_ELTS` through the docs

**Comment by myrrlyn** [comment]
It's `usize::max_value() >> 3 >> mem::size_of::<T>()`, if you're curious. I haven't yet figured out how to handle the fact that this implementation detail does constrain the public API while not actually exposing the implementation itself. `BitPtr` and everything associated with it are opaque internal details that I take great pains to hide, but having a smaller theoretical maximum than `Vec` or slice is information that I nevertheless need to provide.

I don't recall if `cargo doc --document-private-items` applies transitively, but right now that's the only way to read the docs for `BitPtr` and other internal-only components.

Note to self: the current arithmetic of `MAX_ELTS` is also *incorrect*, in that it computes the maximum `u8` rather than the maximum `T`.

**Comment by myrrlyn** [comment]
These constants will be reëxported under `BitSlice` in the 0.18 release. I will close this when I publish it.

**Comment by myrrlyn** [comment]
Now documented as an exported constant under `BitSlice`, as seen [here](https://docs.rs/bitvec/0.18.0/bitvec/slice/struct.BitSlice.html#associatedconstant.MAX_ELTS). Thanks!
