### ISSUE TITLE
How to create a BitVec from a u64

### ISSUE THREAD

**Issue by ironhaven** [myrrlyn/bitvec#61]
I am writing a program where i need to get a rolling window of 3 booleans. I saw the `windows` method in the docs so my plan is to create a `BitVec` from a u64 generated by the rand crate and iterate through windows of bits.

I did not see a example of creating a `BitVec` from a regular unsigned number so i ask what is the best way to do that. Thanks

**Comment by ironhaven** [comment]
After closer inspection of the docs, `u64` implements `BitStore` so it can be borrowed as a `BitSlice`. This gives me the methods i want. I feel this could be documented better.

Now i have run into the issue is that i also need this window to be infinite. My first idea is to `windows` over the `u64`, chop off the first 61 bits (not sure how to do this), then add another `u64` to the end.

How do i reverse truncate a `BitVec`?

**Comment by myrrlyn** [comment]
`BitSlice` has the `from_element` constructor function, which borrows an unsigned integer and produces a `&BitSlice` over it; in addition, there is a trait in the `bitvec` prelude which provides the `.bits::<Order>()` method on unsigned integers, as well as arrays and slices of them. I will ensure that these examples are in the README and crate root documentation.

The `.windows(3)` method will produce a sliding iterator over three consecutive bits in the slice; however, since `BitSlice` is not a ring, it is unable to express an infinitely cycling window that wraps from the back of the slice to the front.

A possible solution is to copy the randomly generated element into a `[u64; 2]` and put that in a wrapper `struct` like this:

```rust
pub struct InfiniteWindows {
  data: [u64; 2];
  current: usize;
}

impl InfiniteWindows {
  pub fn from_element(elem: u64) -> Self {
    Self {
      data: [elem; 2],
      current: 0,
    }
  }

  fn view_bits(&self) -> &BitSlice<AnOrdering, u64> {
    &self.data.bits::<AnOrdering>()[.. 66]
  }
}

impl<'a> Iterator for InfiniteWindows {
  type Item = &'a BitSlice<AnOrdering, u64>;

  fn next(&'a mut self) -> Option<Self::Item> {
    let out = &self.view_bits()[self.current ..][.. 3];
    self.current += 1;
    self.current %= 66;
  }
}
```

This will produce windows over the stored bits, where the subslices `[62 .. 65]` and `[63 .. 66]` appear to wrap from the back to the front. You can extend the iteration as needed for reverse and jumps; seeking in the iterator is just addition or subtraction of the counter that wraps from 66 to 0.

I can't promise offhand that this does not have lifetime issues; I am writing it from memory and not running it through the compiler. If it complains about lifetimes, you can change the structure to take a borrowed bit-slice rather than an owned array.

Unfortunately, I do not yet have the ability to produce immediate values with a bit-precision lens attached, so everything must be done through borrows. I have been working on a design for this, but without const-generics, it's hard to come up with a satisfying one.

Let me know if this works, and how else I can help.

**Comment by myrrlyn** [comment]
Current `develop` branch, and forthcoming `0.18` release, adds the `BitArray` type to be able to wrap any (subject to `std` limitations) array of elements as a `BitSlice`. I am going to close this issue, but please feel free to re&ouml;pen if you still have questions.
