### ISSUE TITLE
count_ones() gives wrong result for BitSlice

### ISSUE THREAD

**Issue by geq1t** [myrrlyn/bitvec#7]
Using bitvec 0.10, counting 1 bits in a bit slice within a single storage unit returns the total number of bits within the slice, not the number of 1 bits. Interestingly, it does work across when operating across byte boundaries. The following program:
```
fn main()
{
    let bits: [u8; 2] = [0b00111100, 0b11001100];
    let bv: bitvec::BitVec = (&bits as &[u8]).into();

    // Here, count_ones() fails
    let bs = &bv[4..8];
    println!("{} {}", bs, bs.count_ones());

    // Here, it works
    let bs = &bv[6..10];
    println!("{} {}", bs, bs.count_ones());
}
```
returns the following output
```
[1100] 4
[00, 11] 2
```

**Comment by myrrlyn** [comment]
Hi! Thanks so much for your report. The bug here is pretty embarrassing in how it got overlooked. The diff here is just inserting the correct `.filter` call in the sole-element case; I'd managed to forget to do that in both `count_ones` **and** `count_zeros`, and never noticed.

I've published `0.10.1` to https://crates.io/crates/bitvec; you should be able to get the fix with a `cargo update` command.

**Comment by myrrlyn** [comment]
@geq1t, I've been looking through the git history of this bug and I want to take a minute to say how extremely thankful I am not only for opening this issue but for the information you provided. The test case you gave reproduced, and your sentence,

> Interestingly, it does work across when operating across byte boundaries.

Told me *exactly* what the error was while I was reading the email, before I'd even opened my editor. This was a great report; thanks for using `bitvec` and I hope it's working well for you!

**Comment by geq1t** [comment]
Thanks for fixing this so quickly! I'm glad the bug report was useful. I'll give it a try again next week, but other duties call right now.
