### ISSUE TITLE
bits! macro fails to expand when invoked from another macro

### ISSUE THREAD

**Issue by calebsander** [myrrlyn/bitvec#70]
I was working on a large macro that passes some of its arguments to `bitvec![]`. Here is a minimized version of it:
```rust
macro_rules! bv {
	($($value:expr)*) => {
		bitvec::bits![$($value:expr),*]
	}
}
```
Now I would expect `bv![0]` to expand to `bitvec::bits![0]`, and that to also successfully expand. However, I see the following compiler error:
```
error: expected identifier, found `0`
  --> src/test.rs:3:19
   |
 3 |         bitvec::bits![$($value:expr),*]
   |                         ^^^^^^ expected identifier
...
 6 | bv![0];
   | ------- in this macro invocation
   |
  ::: /Users/csander/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.17.4/src/macros.rs:64:6
   |
64 |     ($order:path, $store:ident; $($val:expr),* $(,)?) => {{
   |      ----------- while parsing argument for this `path` macro fragment
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
`trace_macros` shows the macro expansion stacktrace:
```
note: trace_macro
  --> src/test.rs:6:1
  |
6 | bv![0];
  | ^^^^^^^
  |
   = note: expanding `bv! { 0 }`
   = note: to `bitvec :: bits ! [0 : expr]`
   = note: expanding `bits! { 0 : expr }`
```
I'm pretty new to Rust macros, so it's not clear to me why this is not matched by the `($($val:expr),* $(,)?)` pattern for `bits!`. Maybe the patterns need to be reordered so this one is tried earlier? Interestingly, `bitvec::bits![0]` expands without any issue when not used inside another macro. Replacing `bitvec::bits!` with `vec!` does allow the code to compile.

**Comment by myrrlyn** [comment]
`macro_rules!` has syntax *somewhat* like a function: in the signature, it takes a list of variable names *and their types*, but in the body, you only refer to the names. Your body should be

```rust
macro_rules! bv {
  ($($value:expr)*) => {
    bitvec::bits![$($value),*]
  };
}
```

Note that when your macro calls mine, it only uses `$($value)*`, without the `:expr` token type marker. Once the arm is entered, the token type is fixed, and doesn't need to be named anymore.

In the `trace_macros` output, you can see how the compiler interprets `$value:expr` in the macro body to be literally the token stream `$value COLON IDENT(expr)`. Since `bits!` is not prepared to handle those tokens, it crashes.

This is a weird part of the language to try to teach, and I did the exact same thing when I was first learning macros. Thanks for filing the report! I'm going to mark this as closed, since it's not an error in the library. I hope this explanation helped.

**Comment by calebsander** [comment]
Ah sorry, I mis-transcribed that macro. I was seeing the same issue with the version you suggested. I've updated the issue description.
