### ISSUE TITLE
BitVec::truncate doesn't always clear data.

### ISSUE THREAD

**Issue by XAMPPRocky** [myrrlyn/bitvec#72]
Hello I was using bitvec in a project that I have been fuzzing and I ran into this case where bitvec still leaves the underlying data. You can run the below code, you can see that the debug representation of bitvec shows the correct state but when trying to convert that back into a slice that data is still present.

```rust
fn main () {
    const DATA: &[u8] = &[0, 220];
    let mut b = BitVec::from_vec(DATA.to_owned());
    b.truncate(b.len() - 4);

    println!("{:?}", b);
    assert_ne!(DATA, b.as_slice());
}
```

**Comment by myrrlyn** [comment]
[`Vec::truncate`](https://github.com/rust-lang/rust/blob/master/library/alloc/src/vec.rs#L736-L753) does not zero-clobber truncated objects. I have kept this behavior, as neither the system allocator nor the container I am emulating provide a guaranteed value for uninitialized memory.

In general, I am of the opinion that `bitvec` should not write to memory unless explicitly asked, because the process of writing to memory is more computationally expensive for `bitvec` than it is for ordinary sequence types.

I have experimented in the past with a `.clear_uninit()` method that sets all uninitialized memory outside of the live view of a `BitVec` or `BitBox` to zero, but have demurred on including it so far.

Currently, the best way to erase memory governed by `bitvec` is to use `[len - 4 ..].set_all(false)` before resizing the vector; since this is not the first time the need to control uninitialized, allocated, bits has come up, I will add a function to do that.
