### ISSUE TITLE
The type parameter of BitView::view_bits{,_mut} should default to LocalBits

### ISSUE THREAD

**Issue by ketsuban** [myrrlyn/bitvec#73]
Currently `BitView::view_bits` and `BitView::view_bits_mut` require specifying an ordering, but `LocalBits` seems like a reasonable default that most people will choose unless they know they're doing something cool. This would reduce the amount of noise when using bitvec to implement bitfields. For example...

```rust
use bitvec::prelude::*;
use core::convert::TryFrom;
use derive_try_from_primitive::TryFromPrimitive;

#[derive(Clone, Copy, Debug, PartialEq, Eq, TryFromPrimitive)]
#[repr(u16)]
pub enum Mode {
    Character0 = 0,
    Character1 = 1,
    Character2 = 2,
    Bitmap0 = 3,
    Bitmap1 = 4,
    Bitmap2 = 5,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(transparent)]
pub struct Control(u16);

impl Control {
    pub fn get_mode(&self) -> Result<Mode, u16> {
        //Mode::try_from(self.0.view_bits::<LocalBits>()[0..2].load::<u16>())
        Mode::try_from(self.0.view_bits()[0..2].load::<u16>())
    }

    pub fn set_mode(&mut self, mode: Mode) {
        //self.0.view_bits_mut::<LocalBits>()[0..2].store(mode as u16)
        self.0.view_bits_mut()[0..2].store(mode as u16)
    }
}
```

**Comment by myrrlyn** [comment]
Per rust-lang/rust#36887, functions may not have default type parameters; default type parameters are accepted only in `struct`, `enum`, `type`, or `trait` definitions. 

The easiest way to accomplish the behavior in your example is to use `BitArray<LocalBits /* or other */, u16>` instead of `u16` as your interior type. I will add documentation to suggest this pattern.
