### ISSUE TITLE
No way to write the underlying `T` to a `&mut BitVec<_, T>`

### ISSUE THREAD

**Issue by reinerp** [myrrlyn/bitvec#79]
I'm using a `bitvec` to implement a bit-oriented serialization library. I'd like to do fast writes of `u64` values to a `&mut BitVec<Lsb0, u64>` and I'd like to generate code consisting of two `u64` loads, two shifts, two ORs, and two `u64` stores.

The only way I can find to express the `u64` write is the following:

```rust
pub fn write_u64(dst: &mut BitSlice<Lsb0, u64>, v: u64) {
    dst.copy_from_bitslice(BitSlice::<Lsb0, u64>::from_element(&v))
}
```

My problem is that `copy_from_bitslice` is very slow: it copies a single bit at a time, rather than a whole `u64` register at a time: 				`self.set_unchecked(idx, *src.get_unchecked(idx));`. In my end-to-end application, which does a lot more than just this serialization/deserialization, my program spends fully 30% of its time in this bit-at-a-time copying.

Is there a way I can write an entire `u64` register at a time? Perhaps `copy_from_bitslice` could be extended to operate in this faster way? (I'm ok with the alignment and masking required when operating at a register at a time, since the `BitSlice` might not be 64-bit aligned.)

**Comment by reinerp** [comment]
Ah, I just found the `BitField` trait, which solves this problem. My big concern is resolved.

Some minor things that might help:
* in `copy_from_bitslice` documentation, mention it does a bit-at-a-time copy, and include a link to the `BitField` trait for doing fast copies
* consider optimizing `copy_from_bitslice` for word-at-a-time copies

**Comment by myrrlyn** [comment]
I wrote a `memcpy`-accelerated version of `.copy_from_bitslice()` and ran it through Criterion on transfer sizes of `1` through `128` kibibits.

Short version: the extra code complexity has very little effect. Even on massive inputs. I have no idea why. Here are the Criterion reports: `accel` uses `[T]::copy_from_slice` to perform bulk move; `bitwise` uses ordinary bit-by-bit iteration. These images aren't great, because they're not scaled to each other, but you can see that the two plots are very close to each other.

<details>

![`memcpy`-accelerated](https://user-images.githubusercontent.com/5921109/94888198-8ff66700-0435-11eb-9eb3-93e694cd5bc0.png)
![bitwise crawl](https://user-images.githubusercontent.com/5921109/94888200-908efd80-0435-11eb-82bd-8ec57c09230a.png)

</details>

The detailed charts for each kibibit section show that the `memcpy`-accelerated version is slightly faster than the bitwise crawl — at 128 Kib, the accelerated takes 180 microseconds, and the bitwise takes 183 microseconds.

Commit 3215f44 accelerates `.copy_from_bitslice()` and links to `BitField::store` in the documentation. This is published as `0.19.3` and available for use.

**Comment by reinerp** [comment]
I think I've found the issue. In Commit 3215f44, you seem to be missing an early return from the `memcpy`-accelerated version. So when the `memcpy`-accelerated version runs, it will run the fast implementation, and then also run the slow implementation. Presumably it should return from the function after the fast implementation has completed.

That said, I was surprised to see a `memcpy`-accelerated implementation. Sure, that's nice when it fires, but it requires the `head` indices to match, which they often won't. Even if the `head` indices don't match (making `memcpy` impossible), it's possible to do much better than bitwise copy, by operating on a `T` word at a time, and doing the appropriate bitshifts to fix up the alignment. For example, a loop which calls into `BitField::load` (from `src`) and `BitField::store` (to `dst`) would be fairly close to optimal. For `T=u64`, at a rough guess this might be ~64x faster on long bitslices.

**Comment by myrrlyn** [comment]
…

I clearly need a second reviewer. Putting in an `else` clause gives the expected acceleration. Thanks for the catch.

Without specialization, `BitField` can only be implemented on individual orderings of `BitSlice`, and `.copy_from_bitslice` can be implemented only as either a general method for *all* ordering parameters, xor a specific method on *each known* ordering parameter. Since it is in the `[bool]` API, I have to keep it in the fully-generalized `BitSlice<O, T>` API, rather than in partially-specified `BitSlice<_, T>` blocks.

*However*, specialization can be faked through `TypeId`, and you're right: `BitField` is *way* faster than a crawl, even with a shift applied.

Thank you again for this report, and for checking my work.

<details>

![memcpy](https://user-images.githubusercontent.com/5921109/94999253-7d834700-0575-11eb-8c99-9dd86836086d.png)
![load_store](https://user-images.githubusercontent.com/5921109/94999257-7eb47400-0575-11eb-8898-08c9ae334cec.png)
![bitwise](https://user-images.githubusercontent.com/5921109/94999256-7e1bdd80-0575-11eb-9328-2ebb8211d60c.png)
![mismatch](https://user-images.githubusercontent.com/5921109/94999255-7e1bdd80-0575-11eb-8243-740d1cb68221.png)


</details>

**Comment by myrrlyn** [comment]
The accelerated behavior is incorrect when used on slices of the same order but different storage. I have reverted the accelerated behavior back solely to `.copy_from_bitslice()`, but it will be present in the next release.
