### ISSUE TITLE
BitVec safe to send between threads

### ISSUE THREAD

**Issue by ratorx** [myrrlyn/bitvec#8]
Is BitVec safe to send to another thread?

In the latest version of the crate, !Send is derived, however in the past, this was not the case. I was wondering whether this is deliberate?

**Comment by myrrlyn** [comment]
`&BitSlice` should be `Sync`, all other types should be `Send`. I honestly hadn't thought about those traits at all. I will add those implementations. Thanks for the note!

Alexander Payne
Satellite Software Engineer
________________________________

**Comment by ratorx** [comment]
Thanks for the quick reply! Do you think you can give an ETA for when the update might be pushed? I don't mean to rush you, but I'm using this crate in a project that's due pretty soon.

**Comment by myrrlyn** [comment]
Right now.

**Comment by ratorx** [comment]
Thanks a lot!

**Comment by myrrlyn** [comment]
I just realized that there is now the possibility for a race condition when fragmenting a `&mut BitSlice` into multiple regions using `split_at_mut`, where those smaller regions do not end at element boundaries.

The following code:

```rust
use bitvec::prelude::*;
use std::thread;
let src: &mut [u8] = &mut [0];

{
let bs: &mut BitSlice = src.into();
let (left, right): (&mut BitSlice, &mut BitSlice) = bs.split_at(4);
let l = thread::spawn(|| left.set(1, true));
let r = thread::spawn(|| right.set(1, true))
l.join();
r.join();
}

println!("{:02X}", src[0]);
```

shows the race condition. At the end of execution, the value of `src[0]` is able to validly be `0x40`, `0x04`, or `0x44`.

I don't think I can prevent this at the type system without changing the `Bits` trait to use the Atomic variants of the storage elements and/or using fenced instructions in the bit setter function.

At present, the most I can do is say very loudly **do not write concurrently to bit regions that share underlying memory**. I'll come up with a solution in the near future, but for now, that's a pretty easy problem to avoid.

**Comment by ratorx** [comment]
Is there any particular reason that BitVec is not Sync? In the standard library Vec is Sync and I don't see any reason why using multiple shared references to BitVec from different threads would cause issues (it doesn't use interior mutability afaik).

**Comment by myrrlyn** [comment]
Honestly, I don't know very much about concurrency safety and so I'm mostly just trying to be conservative about doing something that can wind up causing unsound behavior. Shortly after implementing the marker traits in this PR, I realized that the `Send` impl permitted race conditions in two neighboring, non-overlapping, `&mut BitSlice` handles, so concurrency in general has me nervous about correctness.

From the [`Sync`] docs,

> The precise definition is: a type `T` is `Sync` if and only if `&T` is `Send`.

since `&BitSlice` is `Send`, and `&BitBox` and `&BitVec` are similarly read-only, I think you're right, and that it is improper for `BitBox` and `BitVec` to not be `Sync`.

[`Sync`]: https://doc.rust-lang.org/std/marker/trait.Sync.html

**Comment by myrrlyn** [comment]
Commit 7eb347c adds `Sync` impls to `BitBox` and `BitVec`. This commit is tagged as `v0.11.2`, and I will publish it to crates.io at some point today.
