### ISSUE TITLE
BitVec.count_ones seems wrong

### ISSUE THREAD

**Issue by grenierdev** [myrrlyn/bitvec#84]
I'm having a hard time with `count_ones`. It does not seem to reflect the actual ones in the slice returned by `as_slice`. If I use the same slice to reconstruct a `BitVec<Lsb0, u8>`, I get a different count.

```rust
let buffer = mask.as_slice(); // mask is a BitVec<Lsb0, u8>
// buffer is [240, 1, 127, 240, 31, 255, 231, 255, 252, 159, 255, 255, 95, 255, 227, 127, 248, 31, 255, 247, 255, 254, 159, 255, 225, 63, 248, 3, 127, 252]
let mask2: BitVec<Lsb0, u8> = BitVec::from_vec(buffer.to_vec());
println!("{} {}", mask.count_ones(), mask2.count_ones());
// 175 181
```
The correct count is `175`. Am I doing something wrong?

**Comment by myrrlyn** [comment]
Check that `assert_eq!(mask, mask2);` succeeds. I strongly suspect that it does not.

The total count of one-bits in `buffer` is 181, which you can test with `mask.as_slice().iter().copied().map(u8::count_ones).sum::<u32>()`. 

However, `BitSlice::count_ones` only counts within the subset of bits in memory that it considers alive. `mask.len()` is *probably* 234 or so, and the six high bits of the last byte are not being included in the count.

The count is expanding from 175 to 181 because constructing a new bit-vector over a memory buffer sets it to cover every bit in the buffer, including any garbage bits that `mask` had been ignoring. You can test this by calling `mask.set_uninitialized(false);` before viewing it as a slice; I would bet that this sets the last byte in `buffer` to `0`.

At this point, I would ask how you are constructing `mask`; I try to have all garbage bits in the buffer set to zero by default, not one, and it generally takes some deliberate fiddling to get a buffer that has garbage ones.

**Comment by grenierdev** [comment]
@myrrlyn I am initializing with `bitvec![Lsb0, u8; 1; (size.w * size.h) as usize]`, thus the _extra bits_ were set to `1`.

Since I'm working with immutable data, I placed the `mask.set_uninitialized(false)` right after the initialization.

Now works as I expected. Thanks for the explanation and your time!
