### ISSUE TITLE
.extend_from_bitslice() requires same backing store

### ISSUE THREAD

**Issue by kulp** [myrrlyn/bitvec#85]
It seems that between bitvec 0.17.4 and bitvec 0.19.3, extending a `bitvec` from a slice became more restrictive.

[v0.19.3's `extend_from_bitslice` needs bit-ordering and bit store to match.](https://docs.rs/bitvec/0.19.3/bitvec/vec/struct.BitVec.html#method.extend_from_bitslice)

[v0.17.4's `extend_from_slice` also appears to need the same matching.](https://docs.rs/bitvec/0.17.4/bitvec/vec/struct.BitVec.html#method.extend_from_slice)

Despite this similarity, I see apparently different behavior :

[This does not compile on v0.19.3.](https://github.com/kulp/bitvec-debugging/blob/af1559794bf15e0ac50dc51ee6cfb9d34d78a06c/src/lib.rs)

[This, however, does compile on v0.17.4.](https://github.com/kulp/bitvec-debugging/commit/0edc1b1651745e3a6697831fec408ed5ea3f93c6#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759)

Possibly this is because `BitBox` has a different type ? Somehow, type inference seems to be involved.

My expectation would be that it would be possible to extend a bitvec using a bitvec of any bit ordering, or at least of any underlying `BitStore` size. Is that a bad expectation ?

Sorry for the rushed report -- I am about to board a plane. I will review this later and fill in details.

**Comment by myrrlyn** [comment]
This was a casualty of my attempts to accelerate copy behavior where the type parameters matched up. Since I now have a hack to simulate specialization, [the original behavior has already been restored in `develop`](https://github.com/myrrlyn/bitvec/blob/develop/src/vec.rs#L458-L467) and is awaiting a release.

I share the standard library's opinion that the named inherent method is a *semantically* incorrect API, but since the semantically correct API (`<BitVec as Extend<&bool>>::extend`) is currently incapable of performing internal specialization when the extension source is a matching `BitSlice`, the named method is available for performance reasons. However, `.extend_from_bitslice()` does not have any performance benefits when the source `BitSlice` does not match the destination `BitVec`, so calling the inherent method instead of the trait method has no purpose.

Since I had already restored the behavior, and since I cannot mark a function as deprecated conditionally on its monomorphization, I am going to close this and hurry up the `0.20` release. Summary: prefer `.extend()` over `.extend_from_bitslice()` for a heterogenous extension: same behavior, better name. Absolutely use `.extend_from_bitslice()` for a homogenous extension, as `.extend()` is incapable of detecting this case and specializing for it.

**Comment by kulp** [comment]
Thanks. I saw the references to `.extend()` but did not delve into them previously. `.extend()` will probably suffice for now.
