### ISSUE TITLE
Clarification on offset_from

### ISSUE THREAD

**Issue by sharksforarms** [myrrlyn/bitvec#86]
Hey @myrrlyn , just wanted to get clarification on the offset_from function and to make sure it's intended and not a bug.

The documentation states:
```
If the two slices are created from different buffers entirely, a comparison is undefined
```

Consider the following:
```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        use bitvec::prelude::*;

        let bits = bitvec![Msb0, u8; 0, 1 ,1];

        let (left, right) = bits.split_at(3);
        println!("left: {:?}", left);
        println!("right: {:?}", right);
        println!("offset: {:?}", left.offset_from(right));
    }
}
```

The output is:
```
left: [011]
right: []
offset: -1123808794664952
```

Are `left` and `right` not slices of the original buffer? I was expecting a value of 3. I may be misunderstanding.

Thanks

**Comment by myrrlyn** [comment]
The [current implementation of `.split_at()`](https://github.com/myrrlyn/bitvec/blob/develop/src/slice.rs#L1919-L1925) produces the canonical empty slices when splitting at `0` or `self.len()`. This is a behavior difference from `slice::split_at`, which does perform the arithmetic unconditionally; I elected to do so because it is faster to detect edge cases and produce the canonical empty slice value than it is to decode/modify/encode.

However, given that this is a behavior difference from `slice::split_at`, and the purpose of `.offset_from()` is to measure consumption through a buffer, I am inclined to specify that certain empty slices, such as those produced by `.split_at()` and friends, will have the correct base information.

This behavior will be present in the next release series, `0.20`. Please let me know what series you are currently using, and I will backport the change to it and cut a patch.

**Comment by sharksforarms** [comment]
[Deku](https://github.com/sharksforarms/deku) is currently using 0.19 of bitvec. `split_at` is currently used, as you said, to measure consumption through a buffer (i.e. read X bits, manipulate, and return the rest). So far it hasn't been an issue until combining with `offset_from`

Here is a PR which proposes using `offset_from`:
https://github.com/sharksforarms/deku/pull/118/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R514

**Comment by myrrlyn** [comment]
`cargo update` to `0.19.4`.
